"use client";

import * as React from "react";
import { ChevronDown } from "lucide-react";

import { cn } from "@/lib/utils";

const FAQS = [
  {
    q: "How does the AI resume parser work?",
    a: "When a candidate uploads a CV, we extract raw text and send it to an AI model that identifies structured fields — contact info, experience, education, skills, certifications, and more — then populates the candidate profile automatically.",
  },
  {
    q: "How is the ATS score calculated?",
    a: "Each resume is scored across experience, skills, formatting, education, and achievements, plus keyword density and recruiter readability. Scores are generated by an AI model and are fully explainable with specific suggestions.",
  },
  {
    q: "How does AI job matching work?",
    a: "We generate vector embeddings for every resume and job description, then combine semantic similarity search (pgvector) with an AI reasoning pass to produce a match score, strengths, missing skills, and interview probability.",
  },
  {
    q: "Is my data secure?",
    a: "Yes. PRA uses role-based access control, row-level security on every table, encrypted storage, and full audit logging. Only authorized recruiters at your company can see your candidates' data.",
  },
  {
    q: "Can I use PRA without AI features?",
    a: "Yes — every AI feature is additive. You can run the platform as a traditional ATS and enable AI screening, matching, and scoring whenever you're ready.",
  },
];

export function FAQ() {
  const [open, setOpen] = React.useState<number | null>(0);

  return (
    <section id="faq" className="py-24">
      <div className="container max-w-3xl">
        <div className="text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">Frequently asked questions</h2>
        </div>
        <div className="mt-12 divide-y divide-border rounded-2xl border border-border">
          {FAQS.map((faq, i) => (
            <div key={faq.q} className="p-6">
              <button
                className="flex w-full items-center justify-between text-left font-medium"
                onClick={() => setOpen(open === i ? null : i)}
              >
                {faq.q}
                <ChevronDown className={cn("h-4 w-4 shrink-0 transition-transform", open === i && "rotate-180")} />
              </button>
              {open === i && <p className="mt-3 text-sm text-muted-foreground">{faq.a}</p>}
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}
