-- ============================================================================
-- Migration 0007: Applications, ATS Scores, Job Matches, Screening Results
-- ============================================================================

create table public.applications (
  id uuid primary key default uuid_generate_v4(),
  job_id uuid not null references public.jobs(id) on delete cascade,
  candidate_id uuid not null references public.candidates(id) on delete cascade,
  resume_id uuid not null references public.resumes(id) on delete restrict,
  cover_letter_id uuid references public.cover_letters(id) on delete set null,
  status application_status not null default 'submitted',
  status_reason text,
  applied_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (job_id, candidate_id)
);

create index applications_job_idx on public.applications (job_id);
create index applications_candidate_idx on public.applications (candidate_id);
create index applications_status_idx on public.applications (status);

create trigger applications_set_updated_at
  before update on public.applications
  for each row execute function public.set_updated_at();

-- Keep jobs.applications_count in sync.
create or replace function public.increment_job_applications_count()
returns trigger
language plpgsql
as $$
begin
  if (tg_op = 'INSERT') then
    update public.jobs set applications_count = applications_count + 1 where id = new.job_id;
  elsif (tg_op = 'DELETE') then
    update public.jobs set applications_count = greatest(applications_count - 1, 0) where id = old.job_id;
  end if;
  return null;
end;
$$;

create trigger applications_count_trigger
  after insert or delete on public.applications
  for each row execute function public.increment_job_applications_count();

-- ---------------------------------------------------------------------------
-- ATS Scores (per resume, generated by AI)
-- ---------------------------------------------------------------------------

create table public.ats_scores (
  id uuid primary key default uuid_generate_v4(),
  resume_id uuid not null references public.resumes(id) on delete cascade,
  candidate_id uuid not null references public.candidates(id) on delete cascade,
  overall_score int not null check (overall_score between 0 and 100),
  experience_score int check (experience_score between 0 and 100),
  skills_score int check (skills_score between 0 and 100),
  formatting_score int check (formatting_score between 0 and 100),
  education_score int check (education_score between 0 and 100),
  achievements_score int check (achievements_score between 0 and 100),
  keyword_density jsonb,
  recruiter_readability_score int check (recruiter_readability_score between 0 and 100),
  weaknesses text[],
  suggestions text[],
  ai_model text,
  ai_raw_response jsonb,
  created_at timestamptz not null default now()
);

create index ats_scores_resume_idx on public.ats_scores (resume_id);
create index ats_scores_candidate_idx on public.ats_scores (candidate_id);

-- ---------------------------------------------------------------------------
-- Job Matches (AI matching engine: resume <-> job)
-- ---------------------------------------------------------------------------

create table public.job_matches (
  id uuid primary key default uuid_generate_v4(),
  job_id uuid not null references public.jobs(id) on delete cascade,
  candidate_id uuid not null references public.candidates(id) on delete cascade,
  resume_id uuid not null references public.resumes(id) on delete cascade,
  match_score numeric(5,2) not null check (match_score between 0 and 100),
  semantic_similarity numeric(6,5),
  strengths text[],
  weaknesses text[],
  missing_skills text[],
  recommended_skills text[],
  match_reasons text[],
  interview_probability numeric(5,2),
  ai_summary text,
  ai_model text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (job_id, candidate_id)
);

create index job_matches_job_idx on public.job_matches (job_id);
create index job_matches_candidate_idx on public.job_matches (candidate_id);
create index job_matches_score_idx on public.job_matches (match_score desc);

create trigger job_matches_set_updated_at
  before update on public.job_matches
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Screening Results (per application, deeper AI screening once applied)
-- ---------------------------------------------------------------------------

create table public.screening_results (
  id uuid primary key default uuid_generate_v4(),
  application_id uuid not null references public.applications(id) on delete cascade,
  overall_score int check (overall_score between 0 and 100),
  experience_score int check (experience_score between 0 and 100),
  skill_match_score int check (skill_match_score between 0 and 100),
  education_match_score int check (education_match_score between 0 and 100),
  culture_fit_score int check (culture_fit_score between 0 and 100),
  leadership_score int check (leadership_score between 0 and 100),
  communication_score int check (communication_score between 0 and 100),
  technical_score int check (technical_score between 0 and 100),
  ai_summary text,
  interview_recommendation hiring_recommendation,
  rank_position int,
  ai_model text,
  created_at timestamptz not null default now(),
  unique (application_id)
);

create index screening_results_application_idx on public.screening_results (application_id);
